Add Docker dev environment
wikisource/ia-upload pull request #51
Opened 2021-04-09 16:59 UTC by inductiveload

Based on the same PHP base image as WS-export.

Uses docker-compose for easy remapping of ports, etc.

See also T276925

2021-04-13 22:21 UTC, dayllanmaza requested changes
Looks good except for a couple tiny things.
I don't really know much about this project and it's dependencies but the container runs

2021-04-13 22:21 UTC, dayllanmaza commented on Dockerfile
> +RUN mkdir -p /usr/share/man/man1
I don't think you need this

2021-04-14 00:54 UTC, johnbeard commented on CONTRIBUTING.md
> +8. Install dependencies: `docker compose exec ia-upload composer install`
Good catch (also the 8. in the next line)

2021-04-14 00:55 UTC, johnbeard commented on docker-compose.yml
> +version: "3.9"
¯\_(ツ)_/¯ I haven no clue, I cargo-culted that from somewhere! 3.7 it is.

2021-04-14 00:55 UTC, johnbeard commented on Dockerfile
> +RUN mkdir -p /usr/share/man/man1
OK

2021-04-14 01:31 UTC, inductiveload commented on CONTRIBUTING.md
> +8. Install dependencies: `docker compose exec ia-upload composer install`
Good catch! Also the 8. in the line below.

2021-04-14 01:32 UTC, inductiveload commented on docker-compose.yml
> +version: "3.9"
I cargo-culted that from somewhere, I swear! 3.7 it is.

2021-04-14 01:32 UTC, inductiveload commented on Dockerfile
> +RUN mkdir -p /usr/share/man/man1
OK

2021-06-17 13:10 UTC, inductiveload commented
@samwilson gentle ping?

2021-06-18 00:57 UTC, samwilson reviewed
This looks great! Sorry for not reviewing sooner.

The only tiny change I'd make is to rename the `dev/` directory `docker/`, in line with our other repos.

2021-06-18 01:57 UTC, samwilson commented
Actually, sorry, I think that's far too picky of me! hehe :) let's merge this.

2021-06-18 01:57 UTC, merged

2021-06-18 02:09 UTC, inductiveload commented
> Actually, sorry, I think that's far too picky of me! hehe :) let's merge this.

Always feel free to make changes to any patches of mine if you want :-)